title: Zongjian's blog
description: Personal blog of Zongjian He
url: "https://gh.hezongjian.com"
baseurl: ""

author:
  name: Zongjian He
  email: ""

timezone: Pacific/Auckland

plugins:
  - jekyll-feed

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "fabfile.py"
  - "publishconf.py"
  - "Dockerfile"
  - "external/"
  - "deploy/"
  - "tasks.py"
  - "content"
  - ".bundle"
  - ".jekyll-cache"
  - "vendor"

permalink: /:slug.html

include:
  - "uploads"

theme: minima

minima:
  date_format: "%B %-d, %Y"
  show_excerpts: true

paginate: 10
paginate_path: "/page/:num/"
